apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    database: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      database: mongodb
  template:
    metadata:
      labels:
        database: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
#          command:
#            - mongod
#            - "--auth"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: hostvol
              mountPath: /data/db
#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb
#                  key: mongodb-root-username
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb
#                  key: mongodb-root-password
#            - name: MONGO_INITDB_DATABASE
#              valueFrom:
#                configMapKeyRef:
#                  name: mongodb
#                  key: mongodb-database
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            claimName: mongodb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    database: mongodb