spring:
  profiles:
    active: @profileActive@

---
spring:
  profiles: local
  data:
    mongodb:
      port: 27017
      host: localhost
      database: 'spring-kotlin-restful'
      username: 'spring-kotlin-user'
      password: 'spring-kotlin-pass'

---
spring:
  profiles: docker
  data:
    mongodb:
      port: 27017
      host: mongodb  # Docker container name
      database: 'spring-kotlin-restful'
      username: 'spring-kotlin-user'
      password: 'spring-kotlin-pass'

---
spring:
  profiles: integration-test
  data:
    mongodb:
      database: 'spring-kotlin-restful'
      uri: mongodb+srv://spring:3K8DjsJVQaENF46a@kubernetes-node.dpopz.mongodb.net/spring-kotlin-restful?retryWrites=true&w=majority

---
spring:
  profiles: kubernetes
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}

