name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: MongoDB Action
        uses: sukenda/mongodb-action@v1.0
        with:
          version: '4.2'
          port: 27017
          username: 'root'
          password: 'Pas@123'
          database: 'spring-kotlin-restful'

      - name: Run Sonarqube
        uses: sukenda/sonarqube-action@v1.0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Spring
        run: mvn spring-boot:run -DskipTests -Plocal

      - name: Maven Verify
        run: mvn clean verify sonar:sonar

